### ISSUE TITLE
Brainstorm design language

### ISSUE THREAD

**Issue by iebaker** [jason-h-hu/Wildflower#16]
pls

**Comment by jason-h-hu** [comment]
![wildflower](https://cloud.githubusercontent.com/assets/6496680/19225579/c8c3c426-8e53-11e6-93b1-a2bcaeee763b.png)

**Comment by jason-h-hu** [comment]
![wildflower2](https://cloud.githubusercontent.com/assets/6496680/19225776/af27afb6-8e56-11e6-8f85-0e33c7f942c0.png)

**Comment by iebaker** [comment]
<img width="1103" alt="screen shot 2016-10-09 at 10 36 19 pm" src="https://cloud.githubusercontent.com/assets/4713509/19227593/e3a372b0-8e70-11e6-997e-ed0535e87506.png">
